In [17]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from imblearn.under_sampling import RandomUnderSampler
from sklearn.metrics import confusion_matrix, classification_report, recall_score,f1_score
from joblib import dump, load

In [18]:
data=pd.read_csv('25day_dataset.csv')

In [19]:
label=[]
for i in range(len(data)):
    if data['wahing_machine'].iloc[i] == 0 and data['oven'].iloc[i] == 0 and data['dishwasher'].iloc[i] == 0:
        label.append(0)
    elif data['wahing_machine'].iloc[i] != 0 and data['oven'].iloc[i] == 0 and data['dishwasher'].iloc[i] == 0:
        label.append(1)
    elif data['wahing_machine'].iloc[i] == 0 and data['oven'].iloc[i] != 0 and data['dishwasher'].iloc[i] == 0:
        label.append(2)
    else:
        data['wahing_machine'].iloc[i] == 0 and data['oven'].iloc[i] == 0 and data['dishwasher'].iloc[i] != 0
        label.append(3)
data['classe']=label

In [20]:
Test_set1 =data.loc[(data['DateTime']>='2022-01-01') & (data['DateTime']<'2022-01-02')]
Test_set2 =data.loc[(data['DateTime']>='2022-01-02') & (data['DateTime']<'2022-01-03')]
Test_set3 =data.loc[(data['DateTime']>='2022-01-03') & (data['DateTime']<'2022-01-04')]
Test_set4 =data.loc[(data['DateTime']>='2022-01-04') & (data['DateTime']<'2022-01-05')]
Test_set5 =data.loc[(data['DateTime']>='2022-01-05') & (data['DateTime']<'2022-01-06')]
Test_set6 =data.loc[(data['DateTime']>='2022-01-06') & (data['DateTime']<'2022-01-07')]
Test_set7 =data.loc[(data['DateTime']>='2022-01-07') & (data['DateTime']<'2022-01-08')]
Test_set8 =data.loc[(data['DateTime']>='2022-01-08') & (data['DateTime']<'2022-01-09')]
Test_set9 =data.loc[(data['DateTime']>='2022-01-10') & (data['DateTime']<'2022-01-12')]
Test_set10 =data.loc[(data['DateTime']>='2022-01-12') & (data['DateTime']<'2022-01-13 03:17:00')]

Si carichino i modelli salvati e si eseguono i test per ogni fold.

In [21]:
f_score=[]
recall=[]
Test_list=[Test_set1, Test_set2, Test_set3, Test_set4, Test_set5, Test_set6,Test_set7, Test_set8,Test_set9, Test_set10]
for testing_day in range(len(Test_list)) :
    Test_day=pd.DataFrame(Test_list[testing_day])
    model=load(f'./Modello/model{testing_day+1}.sav')
    
    X_test=Test_day.drop(['DateTime','oven', 'dishwasher', 'wahing_machine','ReactivePower','classe'],axis=1)
    Y_test=Test_day.iloc[:,-1]
    y_predetti=model.predict(X_test)
    
    r = recall_score(Y_test,y_predetti, average= None) 
    f = f1_score(Y_test,y_predetti, average= None)
    f_score.append(f)
    recall.append(r)
    
    print("CM:\n" + str(confusion_matrix(Y_test,y_predetti)) + "\n")
    print(classification_report(Y_test,y_predetti))
    
f_score_res=pd.DataFrame(f_score).replace(0,np.nan)
print("F1_score_Class:\n" + str(f_score_res.mean(axis=0, skipna=True)))
recall_res=pd.DataFrame(recall).replace(0,np.nan)
print("\nRecall_Class:\n" + str(recall_res.mean(axis=0, skipna=True)))

C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: Unde

CM:
[[79419   489    15  1742]
 [  100  3953     0     0]
 [  143     0   539     0]
 [    0     0     0     0]]

              precision    recall  f1-score   support

           0       1.00      0.97      0.98     81665
           1       0.89      0.98      0.93      4053
           2       0.97      0.79      0.87       682
           3       0.00      0.00      0.00         0

    accuracy                           0.97     86400
   macro avg       0.71      0.68      0.70     86400
weighted avg       0.99      0.97      0.98     86400



C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: Unde

CM:
[[76745   917   135   472]
 [  474  6533     0     1]
 [   58     0  1065     0]
 [    0     0     0     0]]

              precision    recall  f1-score   support

           0       0.99      0.98      0.99     78269
           1       0.88      0.93      0.90      7008
           2       0.89      0.95      0.92      1123
           3       0.00      0.00      0.00         0

    accuracy                           0.98     86400
   macro avg       0.69      0.72      0.70     86400
weighted avg       0.98      0.98      0.98     86400

CM:
[[78189   920   821  1165]
 [   47   967    10     0]
 [    0     1   703     0]
 [  375   126     0  3076]]

              precision    recall  f1-score   support

           0       0.99      0.96      0.98     81095
           1       0.48      0.94      0.64      1024
           2       0.46      1.00      0.63       704
           3       0.73      0.86      0.79      3577

    accuracy                           0.96     86400
   macro av

C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: Unde

CM:
[[80334   206   242   973]
 [    0     0     0     0]
 [  379  1341  2923     2]
 [    0     0     0     0]]

              precision    recall  f1-score   support

           0       1.00      0.98      0.99     81755
           1       0.00      0.00      0.00         0
           2       0.92      0.63      0.75      4645
           3       0.00      0.00      0.00         0

    accuracy                           0.96     86400
   macro avg       0.48      0.40      0.43     86400
weighted avg       0.99      0.96      0.98     86400



C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: Unde

CM:
[[81698   697     4   336]
 [   89  3576     0     0]
 [    0     0     0     0]
 [    0     0     0     0]]

              precision    recall  f1-score   support

           0       1.00      0.99      0.99     82735
           1       0.84      0.98      0.90      3665
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0

    accuracy                           0.99     86400
   macro avg       0.46      0.49      0.47     86400
weighted avg       0.99      0.99      0.99     86400



C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: Unde

CM:
[[81204  1004    21   193]
 [    0     0     0     0]
 [    0     0     0     0]
 [   36    35     0  3907]]

              precision    recall  f1-score   support

           0       1.00      0.99      0.99     82422
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         0
           3       0.95      0.98      0.97      3978

    accuracy                           0.99     86400
   macro avg       0.49      0.49      0.49     86400
weighted avg       1.00      0.99      0.99     86400



C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: Unde

CM:
[[79736   573   118   529]
 [  200  3057     1     0]
 [  648     2  1518    18]
 [    0     0     0     0]]

              precision    recall  f1-score   support

           0       0.99      0.98      0.99     80956
           1       0.84      0.94      0.89      3258
           2       0.93      0.69      0.79      2186
           3       0.00      0.00      0.00         0

    accuracy                           0.98     86400
   macro avg       0.69      0.65      0.67     86400
weighted avg       0.98      0.98      0.98     86400



C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: Unde

CM:
[[79152   455   193  1639]
 [   90  4065     0     0]
 [  496    53   257     0]
 [    0     0     0     0]]

              precision    recall  f1-score   support

           0       0.99      0.97      0.98     81439
           1       0.89      0.98      0.93      4155
           2       0.57      0.32      0.41       806
           3       0.00      0.00      0.00         0

    accuracy                           0.97     86400
   macro avg       0.61      0.57      0.58     86400
weighted avg       0.98      0.97      0.97     86400



C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: Unde

CM:
[[166005    946    599    681]
 [   123   2667      0      0]
 [   597      0   1182      0]
 [     0      0      0      0]]

              precision    recall  f1-score   support

           0       1.00      0.99      0.99    168231
           1       0.74      0.96      0.83      2790
           2       0.66      0.66      0.66      1779
           3       0.00      0.00      0.00         0

    accuracy                           0.98    172800
   macro avg       0.60      0.65      0.62    172800
weighted avg       0.99      0.98      0.99    172800

CM:
[[89734   498   278  1943]
 [  262  4099     0     0]
 [   36     1  1369     0]
 [    0     0     0     0]]

              precision    recall  f1-score   support

           0       1.00      0.97      0.98     92453
           1       0.89      0.94      0.92      4361
           2       0.83      0.97      0.90      1406
           3       0.00      0.00      0.00         0

    accuracy                           0.97     9

C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Utente\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: Unde

In [22]:
#f_score_res=pd.DataFrame(f_score).replace(0,np.nan)
#print("F1_score_Mean:\n" + str((f_score_res.mean(axis=0, skipna=True)).mean()))
#recall_res=pd.DataFrame(recall).replace(0,np.nan)
#print("\nRecall_Mean:\n" + str((recall_res.mean(axis=0, skipna=True)).mean()))

F1_score_Mean:
0.8681591963245678

Recall_Mean:
0.9017412338852557


In [23]:
#f_score_res=pd.DataFrame(f_score).replace(0,np.nan)
#print("F1_score_Class:\n" + str(f_score_res.mean(axis=0, skipna=True)))
#recall_res=pd.DataFrame(recall).replace(0,np.nan)
#print("\nRecall_Class:\n" + str(recall_res.mean(axis=0, skipna=True)))

F1_score_Class:
0    0.986898
1    0.867367
2    0.741262
3    0.877110
dtype: float64

Recall_Class:
0    0.978671
1    0.955010
2    0.752239
3    0.921045
dtype: float64


In [33]:
f_score_res

0         1         2         3
0  0.984572  0.930665  0.872168       NaN
1  0.986782  0.903721  0.916918       NaN
2  0.979162  0.636603  0.628239  0.786902
3  0.988921       NaN  0.748528       NaN
4  0.993156  0.900983       NaN       NaN
5  0.992338       NaN       NaN  0.967319
6  0.987198  0.887373  0.794141       NaN
7  0.982175  0.931485  0.409236       NaN
8  0.991205  0.833047  0.664045       NaN
9  0.983467  0.915057  0.896823       NaN

In [29]:
all_off=f_score_res.iloc[:,0]
all_off

0    0.984572
1    0.986782
2    0.979162
3    0.988921
4    0.993156
5    0.992338
6    0.987198
7    0.982175
8    0.991205
9    0.983467
Name: 0, dtype: float64

In [30]:
lavatrice=f_score_res.iloc[:,1]

In [31]:
forno=f_score_res.iloc[:,2]

In [32]:
lavastoviglie=f_score_res.iloc[:,3]

In [38]:
lavatrice_score= pd.concat([all_off, lavatrice], axis=1)
lavatrice_score

0         1
0  0.984572  0.930665
1  0.986782  0.903721
2  0.979162  0.636603
3  0.988921       NaN
4  0.993156  0.900983
5  0.992338       NaN
6  0.987198  0.887373
7  0.982175  0.931485
8  0.991205  0.833047
9  0.983467  0.915057

In [40]:
means_lavatrice=lavatrice_score.mean(axis=1)
means_lavatrice

0    0.957618
1    0.945252
2    0.807882
3    0.988921
4    0.947069
5    0.992338
6    0.937286
7    0.956830
8    0.912126
9    0.949262
dtype: float64

In [41]:
forno_score=pd.concat([all_off, forno], axis=1)

In [43]:
means_forno=forno_score.mean(axis=1)
means_forno

0    0.928370
1    0.951850
2    0.803701
3    0.868724
4    0.993156
5    0.992338
6    0.890669
7    0.695705
8    0.827625
9    0.940145
dtype: float64

In [44]:
lavastoviglie_score=pd.concat([all_off, lavastoviglie], axis=1)

In [47]:
means_lavast=lavastoviglie_score.mean(axis=1)
means_lavast

0    0.984572
1    0.986782
2    0.883032
3    0.988921
4    0.993156
5    0.979828
6    0.987198
7    0.982175
8    0.991205
9    0.983467
dtype: float64

In [48]:
f_score_totale=pd.concat([ means_lavatrice,means_forno,means_lavast], axis=1)
f_score_totale

0         1         2
0  0.957618  0.928370  0.984572
1  0.945252  0.951850  0.986782
2  0.807882  0.803701  0.883032
3  0.988921  0.868724  0.988921
4  0.947069  0.993156  0.993156
5  0.992338  0.992338  0.979828
6  0.937286  0.890669  0.987198
7  0.956830  0.695705  0.982175
8  0.912126  0.827625  0.991205
9  0.949262  0.940145  0.983467

In [50]:
f_score_media=f_score_totale.mean()
f_score_media

0    0.939458
1    0.889228
2    0.976034
dtype: float64

In [51]:
recall_res

0         1         2         3
0  0.972497  0.975327  0.790323       NaN
1  0.980529  0.932220  0.948353       NaN
2  0.964165  0.944336  0.998580  0.859938
3  0.982619       NaN  0.629279       NaN
4  0.987466  0.975716       NaN       NaN
5  0.985222       NaN       NaN  0.982152
6  0.984930  0.938306  0.694419       NaN
7  0.971918  0.978339  0.318859       NaN
8  0.986768  0.955914  0.664418       NaN
9  0.970590  0.939922  0.973684       NaN

In [53]:
all_off_recall=recall_res.iloc[:,0]
all_off_recall

0    0.972497
1    0.980529
2    0.964165
3    0.982619
4    0.987466
5    0.985222
6    0.984930
7    0.971918
8    0.986768
9    0.970590
Name: 0, dtype: float64

In [54]:
lavatrice_rec=recall_res.iloc[:,1]

In [55]:
forno_rec=recall_res.iloc[:,2]

In [56]:
lavast_rec=recall_res.iloc[:,3]

In [57]:
lavatrice_rec= pd.concat([all_off_recall, lavatrice_rec], axis=1)
lavatrice_rec

0         1
0  0.972497  0.975327
1  0.980529  0.932220
2  0.964165  0.944336
3  0.982619       NaN
4  0.987466  0.975716
5  0.985222       NaN
6  0.984930  0.938306
7  0.971918  0.978339
8  0.986768  0.955914
9  0.970590  0.939922

In [58]:
forno_recall= pd.concat([all_off_recall, forno_rec], axis=1)
forno_recall

0         2
0  0.972497  0.790323
1  0.980529  0.948353
2  0.964165  0.998580
3  0.982619  0.629279
4  0.987466       NaN
5  0.985222       NaN
6  0.984930  0.694419
7  0.971918  0.318859
8  0.986768  0.664418
9  0.970590  0.973684

In [59]:
lavastoviglie_recall=pd.concat([all_off_recall, lavast_rec], axis=1)
lavastoviglie_recall

0         3
0  0.972497       NaN
1  0.980529       NaN
2  0.964165  0.859938
3  0.982619       NaN
4  0.987466       NaN
5  0.985222  0.982152
6  0.984930       NaN
7  0.971918       NaN
8  0.986768       NaN
9  0.970590       NaN

In [60]:
means_lavatrice_rec=lavatrice_rec.mean(axis=1)
means_lavatrice_rec

0    0.973912
1    0.956375
2    0.954251
3    0.982619
4    0.981591
5    0.985222
6    0.961618
7    0.975128
8    0.971341
9    0.955256
dtype: float64

In [61]:
means_forno_rec=forno_recall.mean(axis=1)
means_forno_rec

0    0.881410
1    0.964441
2    0.981373
3    0.805949
4    0.987466
5    0.985222
6    0.839675
7    0.645388
8    0.825593
9    0.972137
dtype: float64

In [62]:
means_lavastoviglie_rec=lavastoviglie_recall.mean(axis=1)
means_lavastoviglie_rec

0    0.972497
1    0.980529
2    0.912052
3    0.982619
4    0.987466
5    0.983687
6    0.984930
7    0.971918
8    0.986768
9    0.970590
dtype: float64

In [63]:
recall_totale=pd.concat([ means_lavatrice_rec,means_forno_rec,means_lavastoviglie_rec], axis=1)
recall_totale

0         1         2
0  0.973912  0.881410  0.972497
1  0.956375  0.964441  0.980529
2  0.954251  0.981373  0.912052
3  0.982619  0.805949  0.982619
4  0.981591  0.987466  0.987466
5  0.985222  0.985222  0.983687
6  0.961618  0.839675  0.984930
7  0.975128  0.645388  0.971918
8  0.971341  0.825593  0.986768
9  0.955256  0.972137  0.970590

In [64]:
recall_media=recall_totale.mean()
recall_media

0    0.969731
1    0.888865
2    0.973306
dtype: float64

In [67]:
f_score_media

0    0.939458
1    0.889228
2    0.976034
dtype: float64

In [65]:
recall_media_tot=recall_media.mean()
recall_media_tot

0.9439674443884579

In [66]:
f_score_media_tot=f_score_media.mean()
f_score_media_tot

0.9349067651331041